In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
voc_size=10000

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5038, 3547, 5080, 5462],
 [5038, 3547, 5080, 8470],
 [5038, 7552, 5080, 1723],
 [7700, 2833, 7376, 9544, 7966],
 [7700, 2833, 7376, 9544, 7962],
 [4834, 5038, 201, 5080, 7976],
 [7458, 9024, 3306, 9544]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [14]:
sent_length=6
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0 5038 3547 5080 5462]
 [   0    0 5038 3547 5080 8470]
 [   0    0 5038 7552 5080 1723]
 [   0 7700 2833 7376 9544 7966]
 [   0 7700 2833 7376 9544 7962]
 [   0 4834 5038  201 5080 7976]
 [   0    0 7458 9024 3306 9544]]


In [15]:
## feature representation
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[[ 0.0227919 ,  0.02316325, -0.03453765, -0.02268807,
          0.01522863,  0.02293451, -0.00457967, -0.03494108,
         -0.03283944,  0.01169071],
        [ 0.0227919 ,  0.02316325, -0.03453765, -0.02268807,
          0.01522863,  0.02293451, -0.00457967, -0.03494108,
         -0.03283944,  0.01169071],
        [ 0.02887366,  0.03387945,  0.0198499 , -0.00448715,
         -0.04641388,  0.03572999,  0.03062331, -0.02514279,
          0.04407546, -0.02100145],
        [ 0.01807359, -0.02009995,  0.0416838 ,  0.01113565,
          0.02531284,  0.0429236 , -0.03920772, -0.02480888,
          0.03214742, -0.04135239],
        [ 0.0086931 ,  0.01726511, -0.01642327, -0.03322817,
         -0.01752114, -0.04146619, -0.01999612, -0.00982241,
          0.01463458,  0.04619801],
        [-0.04720533,  0.02101555, -0.03177042,  0.00836065,
         -0.02518882, -0.01174828,  0.01785183, -0.03740985,
          0.04718299,  0.02586544]],

       [[ 0.0227919 ,  0.02316325, -0.03453765, -0

In [24]:
embedded_docs[0]

array([   0,    0, 5038, 3547, 5080, 5462], dtype=int32)

In [25]:
# model.predict(embedded_docs[0])